### ISSUE TITLE
No scrollbar shown on macOS which causes more configuration options not to be revealed

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/tray-electron#113]
Checking the new feature for preset switch from configuration window on macos some configuration elements are not accessible anymore

![image](https://user-images.githubusercontent.com/1957899/150940849-571da248-80ae-4d02-a0a9-0e4adf31c973.png)

**Comment by gbraad** [comment]
No scrollbar? Windows shows the following:

![image](https://user-images.githubusercontent.com/1894/151106893-87b99995-fe06-4825-8cb2-205096e1e75f.png)

Purposely placed the image on top to compare. This is really weird. While still redesigning, as we might place the memory next to the CPU, or so, this is inconsistent at best.

**Comment by gbraad** [comment]
The option of 'pages' or 'tabs' can be added, as adding #71 (Missing proxy options) will make the list even longer.

**Comment by adrianriobo** [comment]
Yeah, I did not compare with windows, but yeah on mac there is no scrollbar :( . Took the picture picking the full window so you can see there was no option (beyond maximize) to see the parameters

**Comment by gbraad** [comment]
>  (beyond maximize) 

These buttons don't work, right?
