### ISSUE TITLE
Show info about required action while changing preset from the tray

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/tray-electron#121]
This is a continuation issue from #120 

### Steps

1. Run onboarding with podman preset
2. Open configuration window change preset to openshift and save
3. Open ministatus window and click start
4. Set pull secret 
5. Click start again

### Expected

Instance should start 

### Actual 

Got a notification about instance is starting but nothing happens, the state on tray or ministatus window keep saying `Stopped`

**Comment by adrianriobo** [comment]
To be able to start `crc setup` is required before click start from tray. As the bundle is not downloaded yet

**Comment by gbraad** [comment]
> As the bundle is not downloaded yet

@praveenkumar what is the expected flow for this on the commandline ?

**Comment by gbraad** [comment]
Will be dealt with as part of

 * #152
 * #153

**Comment by anjannath** [comment]
> > As the bundle is not downloaded yet
> 
> @praveenkumar what is the expected flow for this on the commandline ?

we have to run `crc delete` then `crc setup` after every preset config change using `crc config set preset <preset>`

**Comment by gbraad** [comment]
Dialogs are shown;
  * setup to start the bundle donwload
  * delete request to allow the change of the preset
