### ISSUE TITLE
Introduce/convert to TypeScript

### ISSUE THREAD

**Issue by gbraad** [crc-org/tray-electron#129]
We are now at a point we might wanna consider moving to TypeScript.
Feedback on this is appreciated.

**Comment by evidolob** [comment]
Using `react-scripts` allow to do that very easy, at some point we may mix ts and js for transition period.
Or I can implement  https://github.com/code-ready/tray-electron/issues/125 with ts/tsx and we can discuss on PR transition.

**Comment by evidolob** [comment]
We also need to migrate to TS `code-ready/crc-react-components` as `tsc` complains that it doesn’t have type definitions.

**Comment by gbraad** [comment]
Done
