### ISSUE TITLE
Onboarding and welcome screen

### ISSUE THREAD

**Issue by gbraad** [crc-org/tray-electron#13]
What we actually want to do? Eg.

  * consent question around telemetry
  * automated download of the bundle (progress indicator)
  * ... based on the choice made by the user (what he wants CRC to do; profiles).

_Originally posted by @gbraad in https://github.com/code-ready/tray-electron/pull/12#issuecomment-945721158_

**Comment by gbraad** [comment]
For example

```
  Welcome to CodeReady Containers
   Before you can start using crc, we need to ask you some questions.


                                                         [ Next ]
```

----

```
What would you want to use CRC for?

[ Podman ]    This options will allow you to use podman to run containers
                      inside a VM environment. It will expose the podman command,
[ OpenShift ]   This option will run a full cluster environment as a single node.
                       This option will provide a registry, etc ....

   Note: this can always be changed in the settings dialog

[ Prev ]                                                  [ Next ]
```

----

```
Thank you. You made the following selection
    [ Podman ]
    16 GB of memory
     4 vCPUs
     20 GB of disk space

   {x}    Allow to sent telemetry data to Red Hat
   [ Prev ]                                                        [ OK ]
```

----

```

Setup progress


    Downloading podman bundle ======>............


```

----

```
All set up. CodeReady Container is now ready for use

     [ Open ] a command prompt to use `podman`

     '''
      podman run registry.fedoraproject.org/fedora:latest echo hello
     '''

                                                                   [ Finish ]
```

**Comment by anjannath** [comment]
screenshot of the welcome/onboarding wizard we plan to make as part of the welcome and onboarding flow. It uses the patternfly wizard component (https://www.patternfly.org/v4/components/wizard) 

~earlier: [image](https://user-images.githubusercontent.com/8885742/142590612-7bac027a-4038-436f-93a2-54a6684614a3.png)~

![image](https://user-images.githubusercontent.com/8885742/143186541-2966ead0-d4ec-41da-89cf-b3b9b8f6105f.png)

**Comment by anjannath** [comment]
simple landing/splash screen using patternfly react componenets will need to add styling...

![image](https://user-images.githubusercontent.com/8885742/142834484-df44a686-c8bc-42c6-8d39-2fe4a627efe8.png)

**Comment by anjannath** [comment]
Done in #19
