### ISSUE TITLE
Add pull-secret window

### ISSUE THREAD

**Issue by anjannath** [crc-org/tray-electron#14]
- Ask for pull secret if its not set during start
- Be able to change pull-secret from settings window
- Ask for pull-secret during setup phase from the welcome screen

**Comment by gbraad** [comment]
> Asking for pull-secret during setup from the welcome screeen

This would only work for the OpenShift option. But would it even be possible to open a window and guide through the process to obtain the pull-secret?

**Comment by gbraad** [comment]
@fbricon Do you have some code or a library that can help with obtaining the 'pull-secret' for use with CRC?

**Comment by fbricon** [comment]
@gbraad I think @dgolovin did something similar for vscode-openshift

**Comment by dgolovin** [comment]
@gbraad we are not obtaining pull secret from developers.redhat.com. We just ask user for path to the file with it.

**Comment by gbraad** [comment]
We added a wizard step that asks for the content of the pull-secret, which then gets stored in the keyring.

**Comment by gbraad** [comment]
@fbricon unfortunately not. We are instead storing the contents in the Windows credentials manager or keychain on macOS. We do have an option for the file, but this is Linux only to be honest.
