### ISSUE TITLE
[RFE] Add possibility to switch Kubernetes contexts in tray

### ISSUE THREAD

**Issue by zroubalik** [crc-org/tray-electron#204]
### General information

  * OS: macOS 
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it yes 
  * Running CRC on: Laptop 

## CRC version
```bash
crc version        
CodeReady Containers version: 2.0.1+f0fcd50e
OpenShift version: 4.10.3
Podman version: 3.4.4
```

### Steps to reproduce

  1. Install 2.0.1 and start tray

### Expected
Be able to switch kubernetes contexts in tray

### Actual
After updating to 2.0.1 the tray no longer has an option to switch Kubernetes contexts, this was very neat feature, would like to see it back. Thanks!

**Comment by zroubalik** [comment]
Thanks and sorry, I didn't notice there's a separate tray repo.

**Comment by gbraad** [comment]
We will not add this functionality to the current tray. We hope this can be part of follow-ups to https://github.com/containers/desktop/pull/54

**Comment by gbraad** [comment]
You are free to use the older client for the time being. It is published at the code-ready/tray-macos repo.

**Comment by zroubalik** [comment]
So the current (new) tray is just a temporary solution? Can be the old client used with crc >= 2.0 ?

**Comment by gbraad** [comment]
It wasn't supposed to be a temporary solution. However, things have caught up with us and a new initiative was started. Have a look at: https://github.com/containers/desktop/issues/29

**Comment by gbraad** [comment]
Has been added to the issue. /cc: @evidolob

**Comment by gbraad** [comment]
Closing here
