### ISSUE TITLE
Wrong application provider?

### ISSUE THREAD

**Issue by megascus** [crc-org/tray-electron#224]
The company that provides crc-tray, which appears in the startup of applications that can go from the Windows system settings, is GitHub, Inc. 
Is this intended? 
I think that the name of the company providing the application should be displayed.

I am sorry that the name is not accurate because I am using Windows with Japanese settings.

![image](https://user-images.githubusercontent.com/976085/193370344-9246b461-03b4-4f8b-9fba-2015954cfe71.png)

**Comment by anjannath** [comment]
Thanks for reporting, this comes from electron, we should use `rcedit` to modify this or need to check if `electron-packager` can configure the publisher

**Comment by megascus** [comment]
I think it was installed when I installed openshift local, but I guess I had the wrong github repository to report it. 
I will look for another repository. 
Thanks.

**Comment by praveenkumar** [comment]
This is now correct repo since @anjannath moved it.

**Comment by gbraad** [comment]
@anjannath is this an easy fix?

**Comment by anjannath** [comment]
> @anjannath is this an easy fix?

yes, should an easy fix, need to look at the available flags in `electron-packager` and see if we can set the publisher info or if flags are not available manually have to edit it after the build with `rcedit`

**Comment by anjannath** [comment]
from `electron-packager -h`
```
* win32 target platform only *

win32metadata      a list of sub-properties used to set the application metadata embedded into
                   the executable. They are specified via dot notation,
                   e.g. --win32metadata.CompanyName="Company Inc."
                   or --win32metadata.ProductName="Product"
                   Properties supported:
                   - CompanyName (default: author name from nearest package.json)
                   - FileDescription (default: appname)
                   - OriginalFilename (default: renamed exe)
                   - ProductName (default: appname)
                   - InternalName (default: appname)
                   - requested-execution-level (user, asInvoker, or requireAdministrator)
                   - application-manifest
```

So we could either set `Red Hat` as the `author` in `package.json` or use the `--win32metadat.CompanyName`, i'd prefer the first method
