### ISSUE TITLE
dropdown menu shows mixed menus

### ISSUE THREAD

**Issue by maxandersen** [crc-org/tray-electron#53]
<img width="364" alt="2022-01-03_15-35-35" src="https://user-images.githubusercontent.com/54129/147943021-85382f1b-f0d7-4705-8dc7-c21df83e84b3.png">

just installed and it shows me these two menu overlapping.

Is that intentional?

**Comment by gbraad** [comment]
@maxandersen I have been able to confirm the situation you are describing. It seems both the menu and the window are opening at the same time on macOS. This is not the same on Windows and therefore I was not able to see this. It is a recorded issue from @adrianriobo and will look into resolving this.

**Comment by anjannath** [comment]
I quickly gave this a try today, wanted to differentiate "left click" and "right click" and register separate handlers for it, but it seems on macOS the 'right-click' event is not working, also i couldn't find a way to cancel an event with `event.preventDefault()` or such, as the events for clicks are actually `keyboardEvents`

Need to look more..

**Comment by gbraad** [comment]
> on macOS the 'right-click' event is not working

The mac originally never had the concept of a right-click. How are these modeled as `KeyboardEvents` ?

**Comment by gbraad** [comment]
Using a modifier key is a possible option, but that also means this needs to be shown in the context menu as a function,
