### ISSUE TITLE
Backend failure: maxBuffer length exceeded

### ISSUE THREAD

**Issue by gbraad** [crc-org/tray-electron#56]
Not sure where this comes from, but likely due to the interval:

![image](https://user-images.githubusercontent.com/1894/148066211-06886228-0585-4adf-a97c-5a54bf08bd79.png)

How to repro? Leave it running for the day.

**Comment by gbraad** [comment]
@anjannath did you get this?

**Comment by gbraad** [comment]
When not running the `crc daemon` process, this does not seem to occur. This suggest it is mostly likely related to the `stdout` of the process that is kept in memory for some reason.

**Comment by anjannath** [comment]
we should use `child_process.spawn` which streams the stdio instead of storing in a buffer which is done in case of `child_process.exec`

**Comment by anjannath** [comment]
fixed in #67
