### ISSUE TITLE
CFBundleIdentifier for mac electron tray contains electron

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/tray-electron#82]
Currently `CFBundleIdentifier` value is `com.electron.crc-tray`  this should be reviewed

**Comment by gbraad** [comment]
@anjannath any idea where this is defined?

@adrianriobo can you also specify what the expectation is?

**Comment by anjannath** [comment]
probably comes from `electron-packager` we don't set this anywhere in code, only for windows we set the `AppModelID` here: https://github.com/code-ready/tray-electron/blob/2cf9cedcaf7d7e0578922ed8e86adb886a053702/main.js#L152-L154

Need to set the flag: https://github.com/electron/electron-packager/blob/main/usage.txt#L75

**Comment by adrianriobo** [comment]
Previous value we had for that field was `com.redhat.codeready.containers`

**Comment by gbraad** [comment]
`codeready.containers` would not make a lot of sense.
This should either be `codeready-containers` or `codereadycontainers`.
The questionable bit is therefore `com.electron`. It is expected this is `com.redhat`.

**Comment by adrianriobo** [comment]
@anjannath the attribute you are referring is for windows, sorry for the lack of information but this value `CFBundleIdentifier` is mac related. The value is included in the  `Info.ptlist` file

**Comment by adrianriobo** [comment]
> `codeready.containers` would not make a lot of sense. This should either be `codeready-containers` or `codereadycontainers`. The questionable bit is therefore `com.electron`. It is expected this is `com.redhat`.

Well I guess this can be arguably, as I guess codeready can no be seen as an organizational structure, so you are right. I just added the value which is currently on the releases (so just in case someone somehow is using it, we should add this change to documentation notes).

Also yes,  even changing this value to a more accurate one, the important bit is `com.electron`
