### ISSUE TITLE
[Annoyance] Expected flow on cluster start without pull secret

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/tray-electron#98]
Currently if during the on boarding process for `openshift preset` the pull secret is not given, when we try to start the cluster we got a notification from the tray about it and a window to add the pull secret content is shown.

After save the pull secret we need to click on `start` again to proceed with the cluster initialization.

This is a slightly different behavior from what we got on previous versions... as previously if we try to start the cluster without the pull secret we got the pull secret content window ...but then the start process was resumed without any extra action (click again on start button)

**Comment by gbraad** [comment]
Right. At the moment we aren't modal. This was added in the PR description and will be resolved later. The same modalness is needed in the configuration window.

**Comment by gbraad** [comment]
This is an annoyance, but not a blocker.

**Comment by gbraad** [comment]
Modal message implemented.
